version: '3.5'

services:
  mysql_docker_container:
    container_name: mysql_docker_container
    build: ./mysql_docker_container
    environment:
      MYSQL_DATABASE: 'mysql_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'rpass'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    networks:
      - mpn_network
    volumes:
      - ./mysql_docker_container/etc/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "5101:80"
  php_docker_container:
    container_name: php_docker_container
    build: ./php_docker_container
    networks:
      - mpn_network
    volumes:
      - ./php_docker_container/root:/var/project/root
      - ./php_docker_container/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./php_docker_container/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php_docker_container/usr/local/etc/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    ports:
      - "5102:80"
    depends_on:
      - mysql_docker_container
  nginx_docker_container:
    container_name: nginx_docker_container
    build: ./nginx_docker_container
    networks:
      - mpn_network
    volumes:
      - ./nginx_docker_container/root:/var/project/root
      - ./nginx_docker_container/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_docker_container/sites-available/project.com:/etc/nginx/sites-available/project.com
    ports:
      - "5103:80"
    depends_on:
      - php_docker_container
  varnish_docker_container:
    container_name: varnish_docker_container
    build: ./varnish_docker_container
    environment:
      VARNISH_SIZE: '1G'
    networks:
      - mpn_network
    volumes:
      - ./varnish_docker_container/root:/var/project/root
      - ./varnish_docker_container/default.vcl:/etc/varnish/default.vcl
    ports:
      - "5104:80"
    depends_on:
      - nginx_docker_container
networks:
  mpn_network:
    driver: bridge
    name: mpn_network