FROM mysql:8.0
WORKDIR /var/project/root

##############################################################################
#### Packages installation
##############################################################################
RUN apt-get update
RUN yes | apt-get install nano